#!/usr/bin/env python3
"""Render executed Egison notebooks into the site's SSI content fragments."""

from __future__ import annotations

import argparse
import html
import re
import sys
import tempfile
import warnings
from dataclasses import dataclass, replace
from pathlib import Path
from urllib.parse import quote

import nbformat
from nbconvert import HTMLExporter


REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
BAD_OUTPUT = re.compile(
    r"Type error:|Evaluation error:|Parse error:|Warning:|"
    r"Unbound variable|Restarting Egison|Traceback \(most recent call last\)"
)


@dataclass(frozen=True)
class RenderTarget:
    locale: str
    math_directory: Path
    content_directory: Path
    notebook_directory: Path
    github_directory: str
    raw_directory: str
    resource_label: str
    toolbar_label: str
    source_label: str
    raw_label: str
    article_language: str = ""
    ignored_routes: frozenset[str] = frozenset()


TARGETS = {
    "en": RenderTarget(
        locale="en",
        math_directory=REPOSITORY_ROOT / "math",
        content_directory=REPOSITORY_ROOT / "math" / "contents",
        notebook_directory=REPOSITORY_ROOT.parent / "egison-jupyter" / "math",
        github_directory="https://github.com/egison/egison-jupyter/blob/master/math",
        raw_directory="https://raw.githubusercontent.com/egison/egison-jupyter/master/math",
        resource_label="Notebook resources",
        toolbar_label="Executed Egison notebook",
        source_label="View source on GitHub",
        raw_label="Download .ipynb",
    ),
    "ja": RenderTarget(
        locale="ja",
        math_directory=REPOSITORY_ROOT / "ja" / "math",
        content_directory=REPOSITORY_ROOT / "ja" / "math" / "contents",
        notebook_directory=REPOSITORY_ROOT.parent / "egison-jupyter" / "ja" / "math",
        github_directory="https://github.com/egison/egison-jupyter/blob/master/ja/math",
        raw_directory="https://raw.githubusercontent.com/egison/egison-jupyter/master/ja/math",
        resource_label="Notebookの関連リンク",
        toolbar_label="実行済みEgison Notebook",
        source_label="GitHubでソースを表示",
        raw_label=".ipynbをダウンロード",
        article_language="ja",
        ignored_routes=frozenset({"hodge-laplacian-shperical"}),
    ),
}


def output_strings(value):
    if isinstance(value, str):
        yield value
    elif isinstance(value, list):
        for item in value:
            yield from output_strings(item)
    elif isinstance(value, dict):
        for item in value.values():
            yield from output_strings(item)


def route_slugs(target: RenderTarget) -> set[str]:
    return (
        {path.stem for path in target.math_directory.glob("*.html")}
        - {"index"}
        - set(target.ignored_routes)
    )


def validate_notebook(path: Path):
    notebook = nbformat.read(path, as_version=4)
    nbformat.validate(notebook)
    code_cells = [cell for cell in notebook.cells if cell.cell_type == "code"]

    if not code_cells:
        raise ValueError(f"{path.name}: notebook has no code cells")
    if any(cell.execution_count is None for cell in code_cells):
        raise ValueError(f"{path.name}: every code cell must have a stored execution")

    rich_outputs = 0
    for cell in code_cells:
        for output in cell.outputs:
            if output.output_type == "error":
                raise ValueError(f"{path.name}: contains an error output")
            for text in output_strings(output):
                if BAD_OUTPUT.search(text):
                    raise ValueError(f"{path.name}: contains an Egison/Jupyter error")
            if output.output_type == "display_data" and "text/html" in output.data:
                rich_outputs += 1

    if rich_outputs < 2:
        raise ValueError(f"{path.name}: fewer than two stored HTML math outputs")
    return notebook


def render_fragment(
    exporter: HTMLExporter, path: Path, target: RenderTarget
) -> str:
    notebook = validate_notebook(path)
    body, _ = exporter.from_notebook_node(notebook)
    filename = quote(path.name)
    slug = html.escape(path.stem, quote=True)
    source_url = f"{target.github_directory}/{filename}"
    raw_url = f"{target.raw_directory}/{filename}"
    language = (
        f' lang="{html.escape(target.article_language, quote=True)}"'
        if target.article_language
        else ""
    )
    resource_label = html.escape(target.resource_label, quote=True)
    toolbar_label = html.escape(target.toolbar_label)
    source_label = html.escape(target.source_label)
    raw_label = html.escape(target.raw_label)

    return f"""<!-- Generated by tools/render_math_notebooks.py from {path.name}. -->
<nav class="math-notebook-toolbar" aria-label="{resource_label}">
  <span class="math-notebook-toolbar__label">{toolbar_label}</span>
  <a href="{source_url}">{source_label}</a>
  <a href="{raw_url}" download>{raw_label}</a>
</nav>
<article class="math-notebook tex2jax_process" data-notebook="{slug}"{language}>
{body.strip()}
</article>
"""


def write_atomic(path: Path, content: str) -> None:
    with tempfile.NamedTemporaryFile(
        "w", encoding="utf-8", dir=path.parent, delete=False
    ) as temporary:
        temporary.write(content)
        temporary_path = Path(temporary.name)
    temporary_path.chmod(0o644)
    temporary_path.replace(path)


def render_target(target: RenderTarget, check: bool) -> int:
    notebook_directory = target.notebook_directory.resolve()
    notebooks = {path.stem: path for path in notebook_directory.glob("*.ipynb")}
    routes = route_slugs(target)
    if set(notebooks) != routes:
        missing = sorted(routes - set(notebooks))
        unexpected = sorted(set(notebooks) - routes)
        details = []
        if missing:
            details.append(f"missing notebooks: {', '.join(missing)}")
        if unexpected:
            details.append(f"unexpected notebooks: {', '.join(unexpected)}")
        print("; ".join(details), file=sys.stderr)
        return 1

    exporter = HTMLExporter(template_name="basic")
    exporter.exclude_input_prompt = True
    exporter.exclude_output_prompt = True
    warnings.filterwarnings(
        "ignore", message=r"No lexer found for language 'egison'.*"
    )

    stale: list[Path] = []
    changed = 0
    for slug in sorted(routes):
        destination = target.content_directory / f"{slug}.html"
        rendered = render_fragment(exporter, notebooks[slug], target)
        current = destination.read_text(encoding="utf-8") if destination.exists() else None
        if current == rendered:
            continue
        if check:
            stale.append(destination)
        else:
            write_atomic(destination, rendered)
            changed += 1

    if stale:
        for path in stale:
            print(f"out of date: {path.relative_to(REPOSITORY_ROOT)}", file=sys.stderr)
        return 1

    action = "Verified" if check else "Rendered"
    detail = "" if check else f" ({changed} changed)"
    print(
        f"{action} {len(routes)} {target.locale} mathematics notebook "
        f"fragments{detail}."
    )
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--locale",
        choices=("en", "ja", "all"),
        default="en",
        help="site locale to render (default: en)",
    )
    parser.add_argument(
        "--notebook-dir",
        type=Path,
        help="override the notebook directory for one locale",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify that all generated fragments are current without writing",
    )
    args = parser.parse_args()

    if args.locale == "all" and args.notebook_dir:
        parser.error("--notebook-dir cannot be combined with --locale all")

    locales = tuple(TARGETS) if args.locale == "all" else (args.locale,)
    for locale in locales:
        target = TARGETS[locale]
        if args.notebook_dir:
            target = replace(target, notebook_directory=args.notebook_dir)
        if render_target(target, args.check):
            return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
