#!/usr/bin/env python3
"""Render executed Egison notebooks into the site's SSI content fragments."""

from __future__ import annotations

import argparse
import html
import re
import sys
import tempfile
import warnings
from pathlib import Path
from urllib.parse import quote

import nbformat
from nbconvert import HTMLExporter


REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
MATH_DIRECTORY = REPOSITORY_ROOT / "math"
CONTENT_DIRECTORY = MATH_DIRECTORY / "contents"
DEFAULT_NOTEBOOK_DIRECTORY = REPOSITORY_ROOT.parent / "egison-jupyter" / "math"
GITHUB_DIRECTORY = "https://github.com/egison/egison-jupyter/blob/master/math"
RAW_DIRECTORY = "https://raw.githubusercontent.com/egison/egison-jupyter/master/math"
BAD_OUTPUT = re.compile(
    r"Type error:|Evaluation error:|Parse error:|Warning:|"
    r"Unbound variable|Restarting Egison|Traceback \(most recent call last\)"
)


def output_strings(value):
    if isinstance(value, str):
        yield value
    elif isinstance(value, list):
        for item in value:
            yield from output_strings(item)
    elif isinstance(value, dict):
        for item in value.values():
            yield from output_strings(item)


def route_slugs() -> set[str]:
    return {path.stem for path in MATH_DIRECTORY.glob("*.html")} - {"index"}


def validate_notebook(path: Path):
    notebook = nbformat.read(path, as_version=4)
    nbformat.validate(notebook)
    code_cells = [cell for cell in notebook.cells if cell.cell_type == "code"]

    if not code_cells:
        raise ValueError(f"{path.name}: notebook has no code cells")
    if any(cell.execution_count is None for cell in code_cells):
        raise ValueError(f"{path.name}: every code cell must have a stored execution")

    rich_outputs = 0
    for cell in code_cells:
        for output in cell.outputs:
            if output.output_type == "error":
                raise ValueError(f"{path.name}: contains an error output")
            for text in output_strings(output):
                if BAD_OUTPUT.search(text):
                    raise ValueError(f"{path.name}: contains an Egison/Jupyter error")
            if output.output_type == "display_data" and "text/html" in output.data:
                rich_outputs += 1

    if rich_outputs < 2:
        raise ValueError(f"{path.name}: fewer than two stored HTML math outputs")
    return notebook


def render_fragment(exporter: HTMLExporter, path: Path) -> str:
    notebook = validate_notebook(path)
    body, _ = exporter.from_notebook_node(notebook)
    filename = quote(path.name)
    slug = html.escape(path.stem, quote=True)
    source_url = f"{GITHUB_DIRECTORY}/{filename}"
    raw_url = f"{RAW_DIRECTORY}/{filename}"

    return f"""<!-- Generated by tools/render_math_notebooks.py from {path.name}. -->
<nav class="math-notebook-toolbar" aria-label="Notebook resources">
  <span class="math-notebook-toolbar__label">Executed Egison notebook</span>
  <a href="{source_url}">View source on GitHub</a>
  <a href="{raw_url}" download>Download .ipynb</a>
</nav>
<article class="math-notebook tex2jax_process" data-notebook="{slug}">
{body.strip()}
</article>
"""


def write_atomic(path: Path, content: str) -> None:
    with tempfile.NamedTemporaryFile(
        "w", encoding="utf-8", dir=path.parent, delete=False
    ) as temporary:
        temporary.write(content)
        temporary_path = Path(temporary.name)
    temporary_path.chmod(0o644)
    temporary_path.replace(path)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--notebook-dir",
        type=Path,
        default=DEFAULT_NOTEBOOK_DIRECTORY,
        help="directory containing the executed mathematics notebooks",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify that all generated fragments are current without writing",
    )
    args = parser.parse_args()

    notebook_directory = args.notebook_dir.resolve()
    notebooks = {path.stem: path for path in notebook_directory.glob("*.ipynb")}
    routes = route_slugs()
    if set(notebooks) != routes:
        missing = sorted(routes - set(notebooks))
        unexpected = sorted(set(notebooks) - routes)
        details = []
        if missing:
            details.append(f"missing notebooks: {', '.join(missing)}")
        if unexpected:
            details.append(f"unexpected notebooks: {', '.join(unexpected)}")
        print("; ".join(details), file=sys.stderr)
        return 1

    exporter = HTMLExporter(template_name="basic")
    exporter.exclude_input_prompt = True
    exporter.exclude_output_prompt = True
    warnings.filterwarnings(
        "ignore", message=r"No lexer found for language 'egison'.*"
    )

    stale: list[Path] = []
    changed = 0
    for slug in sorted(routes):
        destination = CONTENT_DIRECTORY / f"{slug}.html"
        rendered = render_fragment(exporter, notebooks[slug])
        current = destination.read_text(encoding="utf-8") if destination.exists() else None
        if current == rendered:
            continue
        if args.check:
            stale.append(destination)
        else:
            write_atomic(destination, rendered)
            changed += 1

    if stale:
        for path in stale:
            print(f"out of date: {path.relative_to(REPOSITORY_ROOT)}", file=sys.stderr)
        return 1

    action = "Verified" if args.check else "Rendered"
    detail = "" if args.check else f" ({changed} changed)"
    print(f"{action} {len(routes)} mathematics notebook fragments{detail}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
